"""Product Manager agent.

Ingests a high-level user idea and turns it into three structured outputs:
a Product Requirements Document, a set of user stories, and an itemized task
queue with per-task roles and acceptance criteria.
"""

from __future__ import annotations

from typing import Any, Dict, List

from ..models import (
    AgentRole,
    ArtifactKind,
    ArtifactPayload,
    Feature,
    PRDContent,
    TaskQueueContent,
    TaskQueueItem,
    UserStoriesContent,
    UserStory,
)
from .base import AgentContext, BaseAgent
from .specs import FEATURES, match_features

_STOP_WORDS = {"a", "an", "the", "and", "of", "for", "with", "to", "in", "on", "app", "build", "make", "create"}


def derive_project_name(idea: str) -> str:
    """Derive a title-cased project name from the idea text."""
    words = [w for w in idea.replace("-", " ").split() if w.lower() not in _STOP_WORDS]
    meaningful = [w for w in words if len(w) >= 3] or words
    name = " ".join(meaningful[:3]).title()
    return name or "Generated Product"


class ProductManagerAgent(BaseAgent):
    """Turns a raw idea into a PRD, user stories, and an itemized task queue."""

    role = AgentRole.PRODUCT_MANAGER
    display_name = "Product Manager"

    async def _execute(self, context: AgentContext, inputs: Dict[str, Any]) -> List[ArtifactPayload]:
        idea = str(inputs.get("idea", "")).strip()
        reporter, sprint = context.reporter, context.sprint

        await reporter.log(sprint, self.role.value, "info", "Parsing user idea and extracting requirements")
        feature_keys = match_features(idea)
        await reporter.message(
            sprint,
            self.role,
            "orchestrator",
            "info",
            f"Detected {len(feature_keys)} feature areas: {', '.join(feature_keys)}",
        )

        project_name = derive_project_name(idea)
        features = [
            Feature(
                key=key,
                name=FEATURES[key].name,
                description=FEATURES[key].description,
                priority="P1",
            )
            for key in feature_keys
        ]

        prd = PRDContent(
            project_name=project_name,
            overview=(
                f"{project_name} is an automated software product derived from the idea: "
                f'"{idea}". It exposes a REST API and ships with runnable code, '
                "automated tests, and a QA audit generated by a team of specialized agents."
            ),
            goals=[
                f"Deliver a runnable {project_name} service with a documented REST API.",
                "Provide the detected feature set with validated data models and endpoints.",
                "Ship automated tests and a QA audit proving the code is syntactically sound.",
            ],
            target_users=["End users", "Administrators", "Operations team"],
            features=features,
            non_functional_requirements=[
                "The service must start with a single uvicorn command.",
                "All endpoints must validate input and return consistent error shapes.",
                "Generated code must pass an automated QA audit before delivery.",
            ],
            success_metrics=[
                "100% of generated modules parse without syntax errors.",
                "All documented REST endpoints are covered by tests.",
                "QA audit scores every delivered sprint at 60 or above.",
            ],
            assumptions=[
                "The idea is treated as a greenfield build; no legacy constraints apply.",
                "Persistence is in-memory for the generated reference implementation.",
            ],
            risks=[
                "Unclear requirement scope may produce generic feature coverage.",
                "Generated code is a scaffold and may need hardening before production.",
            ],
        )

        stories = [
            UserStory(
                id=f"US-{index + 1:02d}",
                as_a="user",
                i_want=f"to use the {feature.name.lower()}",
                so_that="the product delivers value from the first release",
                priority="P1",
            )
            for index, feature in enumerate(features)
        ]

        task_queue = self._build_task_queue(feature_keys, project_name)

        await reporter.log(sprint, self.role.value, "info", f"Produced PRD with {len(features)} features and {len(task_queue.tasks)} tasks")

        return [
            ArtifactPayload(
                kind=ArtifactKind.PRD,
                title=f"Product Requirements Document — {project_name}",
                content=prd.model_dump(mode="json"),
            ),
            ArtifactPayload(
                kind=ArtifactKind.USER_STORIES,
                title="User Stories",
                content=UserStoriesContent(stories=stories).model_dump(mode="json"),
            ),
            ArtifactPayload(
                kind=ArtifactKind.TASK_QUEUE,
                title="Itemized Task Queue",
                content=task_queue.model_dump(mode="json"),
            ),
        ]

    @staticmethod
    def _build_task_queue(feature_keys: List[str], project_name: str) -> TaskQueueContent:
        """Create an itemized, role-assigned task queue from the feature set."""
        tasks: List[TaskQueueItem] = []

        tasks.append(
            TaskQueueItem(
                id="T-ARCH-01",
                title=f"Design the {project_name} architecture",
                description="Translate the PRD into a folder schema, ERD, and REST API contract.",
                role=AgentRole.ARCHITECT,
                acceptance_criteria=[
                    "Folder schema lists every generated file with a purpose",
                    "ERD covers every feature entity with fields and relations",
                    "API contract documents all endpoints with sample bodies",
                ],
            )
        )

        for index, key in enumerate(feature_keys, start=1):
            feature = FEATURES[key]
            tasks.append(
                TaskQueueItem(
                    id=f"T-DEV-{index:02d}",
                    title=f"Implement {feature.name}",
                    description=feature.description,
                    role=AgentRole.DEVELOPER,
                    feature_key=key,
                    acceptance_criteria=[
                        "Module ships as runnable code with data models",
                        "REST endpoints exist for every documented resource",
                        "Generated tests pass for the module",
                    ],
                )
            )

        tasks.append(
            TaskQueueItem(
                id="T-QA-01",
                title="Audit the generated codebase",
                description="Check every generated file for syntax errors, security flaws, and missing edge cases.",
                role=AgentRole.QA_AUDITOR,
                acceptance_criteria=[
                    "Every .py file parses without syntax errors",
                    "No critical or high severity security findings",
                    "Audit report scores the codebase 60 or above",
                ],
            )
        )

        return TaskQueueContent(tasks=tasks)
